services:
  - type: web
    name: researchblog-rag
    runtime: node
    plan: free
    rootDir: ./server
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
